package PVE::InitSystem;

# Backend-agnostic facade for init-system specific operations: service
# control, resource scopes used to confine VM/CT processes, and timezone
# management.
#
# The concrete backend is selected at build time: PVE::InitSystem::Backend is
# generated by src/Makefile from Backend.pm.in according to the
# PVE_INIT_SYSTEM variable (e.g. driven by debian/rules depending on which
# Debian build profile is active - see debian/control's
# pkg.pve-common.lsbservice profile). Callers must go through this module and
# must not reference a backend module directly, so that they keep working
# unchanged no matter which backend was selected at build time.

use strict;
use warnings;

use PVE::InitSystem::Backend;

my $backend = $PVE::InitSystem::Backend::MODULE;

(my $backend_path = $backend) =~ s{::}{/}g;
require "$backend_path.pm";

my @interface = qw(
    enter_systemd_scope
    wait_for_unit_removed
    is_unit_active
    start_service
    stop_service
    restart_service
    get_timezone
    set_timezone
    list_timezones
);

for my $sym (@interface) {
    no strict 'refs';
    *{$sym} = \&{"${backend}::${sym}"};
}

1;
