package PVE::InitSystem;

# Backend-agnostic facade for init-system specific operations: service
# control and state, resource scopes used to confine VM/CT processes, reading
# the system log, and timezone management.
#
# The concrete backend is selected at build time: PVE::InitSystem::Backend is
# generated by src/Makefile from Backend.pm.in according to the
# PVE_INIT_SYSTEM variable (e.g. driven by debian/rules depending on which
# Debian build profile is active - see debian/control's
# pkg.pve-common.lsbservice profile). Callers must go through this module and
# must not reference a backend module directly, so that they keep working
# unchanged no matter which backend was selected at build time.

use strict;
use warnings;

use PVE::InitSystem::Backend;

my $backend = $PVE::InitSystem::Backend::MODULE;

(my $backend_path = $backend) =~ s{::}{/}g;
require "$backend_path.pm";

my @interface = qw(
    enter_systemd_scope
    set_scope_properties
    stop_scope
    reset_failed
    create_mount
    get_mount
    list_mounts
    remove_mount
    mount_runtime
    wait_for_unit_removed
    is_unit_active
    start_service
    stop_service
    restart_service
    started_by_init
    reload_service
    try_reload_or_restart_service
    enable_service
    disable_service
    service_status
    service_main_pid
    dump_syslog
    read_journal
    get_timezone
    set_timezone
    list_timezones
);

# Only provided by backends that need them, so that callers built for another
# init system (see e.g. qemu-server's PVE_INIT_SYSTEM) don't change at all.
my @optional_interface = qw(
    remove_empty_scope
);

for my $sym (@interface) {
    no strict 'refs';
    *{$sym} = \&{"${backend}::${sym}"};
}

for my $sym (@optional_interface) {
    no strict 'refs';
    *{$sym} = \&{"${backend}::${sym}"} if $backend->can($sym);
}

1;
